---
  # bring service down

  - hosts: webservers
    become: yes
    tasks:
      - service: name=apache2 state=stopped
      - wait_for: port=80 state=drained

  - hosts: loadbalancer
    become: yes
    tasks:
      - service: name=nginx state=stopped
      - wait_for: port=80 state=stopped

# Restart mysql

  - hosts: database
    become: yes
    tasks:
      - service: name=mysql state=restarted
      - wait_for: host={{ ansible_eth1.ipv4.address }} port=3306 state=started


  # Bring stack up

  - hosts: webservers
    become: yes
    tasks:
      - service: name=apache2 state=restarted
      - wait_for: port=80

  - hosts: loadbalancer
    become: yes
    tasks:
      - service: name=nginx state=restarted
      - wait_for: port=80
