---
- hosts: loadbalancer
  become: yes
  tasks:
    - name: verify status service
      command: service nginx status

- hosts: webserver
  become: yes
  tasks:
    - name: verify apache2 service
      command: service apache2 status

- hosts: database
  become: yes
  tasks:
    - name: verify mysql service
      command: service mysql status
